name: ExcelMailSync

on:
  schedule:
    - cron: "0 * * * *"  # cada hora
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install msal requests
      - run: python ExcelMailSync.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_ID: ${{ secrets.USER_ID }}
